# 몫 구하기

* 정수 num1, num2가 매개변수로 주어질 때, num1을 num2로 나눈 몫을 return 하도록 solution 함수를 완성해주세요.

In [1]:
def solution(num1, num2) :
  return (num1 // num2)

##  두 수의 차 

* 정수 num1과 num2가 주어질 때, num1에서 num2를 뺀 값을 return하도록 soltuion 함수를 완성해주세요.

In [ ]:
def solution(num1, num2) :
  return (num1 - num2)

# 두 수의 곱 

* 정수 num1, num2가 매개변수 주어집니다. num1과 num2를 곱한 값을 return 하도록 solution 함수를 완성해주세요.

In [ ]:
def solution(num1, num2) :
  return (num1 * num2)

# 숫자 비교하기

* 정수 num1과 num2가 매개변수로 주어집니다. 두 수가 같으면 1 다르면 -1을 retrun하도록 solution 함수를 완성해주세요.

In [ ]:
def solution(num1, num2) :
  if(num1 == num2) :
    return 1
  else :
    return -1

-1
1
-1

# 나이 출력

* 머쓱이는 40살인 선생님이 몇 년도에 태어났는지 궁금해졌습니다. 나이 age가 주어질 때, 2022년을 기준 출생 연도를 return 하는 solution 함수를 완성해주세요.

In [ ]:
def solution(age) :
  return 2022 - age + 1

1993

# 나머지 구하기

* 정수 num1, num2가 매개변수로 주어질 때, num1를 num2로 나눈 나머지를 return 하도록 solution 함수를 완성해주세요.

In [ ]:
def solution(num1, num2) :
  return num1 % num2

1

# 각도기 

* 각에서 0도 초과 90도 미만은 예각, 90도는 직각, 90도 초과 180도 미만은 둔각 180도는 평각으로 분류합니다. 각 angle이 매개변수로 주어질 때 예각일 때 1, 직각일 때 2, 둔각일 때 3, 평각일 때 4를 return하도록 solution 함수를 완성해주세요.

In [ ]:
def solution(angle) :
  if angle < 90 and angle > 0 :
    return 1
  elif angle == 90 :
    return 2 
  elif angle > 90 and angle < 180 :
    return 3 
  elif angle == 180 :
    return 4
  else :
    print('angle should be between 0 and 180 degrees')

angle should be between 0 and 180 degrees

# 배열의 평균값 

* 정수 배열 numbers가 매개변수로 주어집니다. numbers의 원소의 평균값을 return하도록 solution 함수를 완성해주세요.

In [ ]:
def solution(numbers) :
  return sum(numbers)/len(numbers)

2.0

# 양꼬치

* 머쓱이네 양꼬치 가게는 10인분을 먹으면 음료수 하나를 서비스로 줍니다. 양꼬치는 1인분에 12,000원, 음료수는 2,000원입니다. 정수 n과 k가 매개변수로 주어졌을 때, 양꼬치 n인분과 음료수 k개를 먹었다면 총얼마를 지불해야 하는지 return 하도록 solution 함수를 완성해보세요.

In [ ]:
def solution(n, k) :
  if ( n // 10 )> 0 :
    k -= (n // 10)
  answer = (n * 12000) + (k * 2000)
  return(print(answer,'원', sep = ''))

0
768000원

# 배열 뒤집기 

* 정수가 들어 있는 배열 num_list가 매개변수로 주어집니다. num_list의 원소의 순서를 거꾸로 뒤집은 배열을 return하도록 solution 함수를 완성해주세요.

In [ ]:
def solution(num_list) :
  return num_list[::-1]

[2, 2, 1, 1]

# 배열 두배 만들기 

* 정수 배열 numbers가 매개변수로 주어집니다. numbers의 각 원소에 두배한 원소를 가진 배열을 return하도록 solution 함수를 완성해주세요.

In [ ]:
def solution(numbers) :
  answer = []
  for i in numbers :
    answer.append(i*2)
  return answer

# 배열 자르기

* 정수 배열 numbers와 정수 num1, num2가 매개변수로 주어질 때, numbers의 num1번 째 인덱스부터 num2번째 인덱스까지 자른 정수 배열을 return 하도록 solution 함수를 완성해보세요.

In [ ]:
def solution(numbers, num1, num2) :
  return numbers[num1:num2+1]

[2, 3, 4]

# 중복된 숫자 개수

* 정수가 담긴 배열 array와 정수 n이 매개변수로 주어질 때, array에 n이 몇 개 있는 지를 return 하도록 solution 함수를 완성해보세요.

In [2]:
def solution(array, n) :
  return array.count(n)

# 특정 문자 제거하기

* 문자열 my_string과 문자 letter이 매개변수로 주어집니다. my_string에서 letter를 제거한 문자열을 return하도록 solution 함수를 완성해주세요.

In [6]:
def solution(my_string, letter) :
    return "".join(my_string.split(letter))

solution('asdf','f')

'asd'

# 점의 위치 구하기 

* 사분면은 한 평면을 x축과 y축을 기준으로 나눈 네 부분입니다. 사분면은 아래와 같이 1부터 4까지 번호를매깁니다.

In [4]:
def solution(x, y) :
    if x > 0 and y > 0 :
        return 1
    elif x < 0 and y > 0 :
        return 2
    elif x < 0 and y < 0 :
        return 3
    elif x > 0 and y < 0 :
        return 4
    else :
        return print('origin')

solution(1, -1)

4

# 짝수 홀수 개수

* 정수가 담긴 리스트 num_list가 주어질 때, num_list의 원소 중 짝수와 홀수의 개수를 담은 배열을 return 하도록 solution 함수를 완성해보세요.